behaviors:
  RLPilot:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 2.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    # Self-play configuration for competitive training
    self_play:
      window: 10                        # Number of past policies to keep
      play_against_latest_model_ratio: 0.5  # 50% chance to play against current model
      save_steps: 50000                 # Save policy snapshot every 50k steps  
      swap_steps: 10000                 # Change opponent every 10k steps
      team_change: 500000               # Switch which team is learning every 500k steps

    max_steps: 10000000
    summary_freq: 20000
    time_horizon: 1024
    keep_checkpoints: 5
    checkpoint_interval: 500000

# Randomized environment parameters for robust self-play training
environment_parameters:
  arena_size:
    sampler_type: uniform
    sampler_parameters:
      min_value: 40     # Minimum arena size (challenging)
      max_value: 80     # Maximum arena size (easier to maneuver)
    
  asteroid_density:
    sampler_type: uniform
    sampler_parameters:
      min_value: 0.4    # Light asteroid field
      max_value: 0.8    # Dense asteroid field