behaviors:
  RLPilot:
    trainer_type: ppo
    
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 3.0e-4
      learning_rate_schedule: linear
      beta: 2.0e-3
      beta_schedule: constant
      epsilon: 0.2
      epsilon_schedule: linear
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
      
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0

    max_steps: 5000000
    summary_freq: 20000
    time_horizon: 1024
    keep_checkpoints: 5

environment_parameters:
  arena_size:
    curriculum:
      - name: Lesson-1
        completion_criteria:
          measure: reward
          behavior: RLPilot
          min_lesson_length: 50
          threshold: 0.6
        value: 60
      - name: Lesson-2
        completion_criteria:
          measure: reward
          behavior: RLPilot
          threshold: 0.6
          min_lesson_length: 50
        value: 50
      - name: Lesson-3
        completion_criteria:
          measure: reward
          behavior: RLPilot
          threshold: 0.6
          min_lesson_length: 50
        value: 40
        
  asteroid_density:
    curriculum:
      - name: Lesson-1
        completion_criteria:
          measure: reward
          behavior: RLPilot
          min_lesson_length: 50
          threshold: 0.6
        value: 0.4
      - name: Lesson-2
        completion_criteria:
          measure: reward
          behavior: RLPilot
          threshold: 0.6
          min_lesson_length: 50
        value: 0.6
      - name: Lesson-3
        completion_criteria:
          measure: reward
          behavior: RLPilot
          threshold: 0.6
          min_lesson_length: 50
        value: 0.8
        
  bot_difficulty:
    curriculum:
      - name: Lesson-1
        completion_criteria:
          measure: reward
          behavior: RLPilot
          min_lesson_length: 50
          threshold: 0.6
        value: 0.4
      - name: Lesson-2
        completion_criteria:
          measure: reward
          behavior: RLPilot
          threshold: 0.6
          min_lesson_length: 50
        value: 0.7
      - name: Lesson-3
        completion_criteria:
          measure: reward
          behavior: RLPilot
          threshold: 0.6
          min_lesson_length: 50
        value: 1.0
